language: python

python:
  - "2.7"
  - "3.6"

matrix:
  include:
    - language: generic
      os: osx

install:
  - mkdir -p ~/bin
  - cp developer/deken ~/bin/deken
  - chmod u+x ~/bin/deken
  - mkdir tmp
  - curl -fsSL -o tmp/deken-test.zip "https://puredata.info/Members/zmoelnig/tests/deken-test.zip"
  - (cd tmp; unzip deken-test.zip; rm deken-test.zip)

script:
  - ~/bin/deken upgrade
  - ./developer/deken package -v000.dekenci tmp/deken-test

after_script:
  - ls -l
  - ls -l tmp/
