language: python

matrix:
  include:
    - language: generic
      os: osx
      env: PIP=pip2
    - python: "2.7"
      env: PIP=pip
    - python: "3.6"
      env: PIP=pip

before_install:
  - export DEKEN_BASE_URL=https://raw.githubusercontent.com/${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}/developer
  - echo ${DEKEN_BASE_URL}

install:
  - mkdir -p ~/bin
  - mkdir -p tmp
  - cp developer/deken ~/bin/deken
  - chmod u+x ~/bin/deken
  - curl -fsSL -o tmp/deken-test.zip "https://puredata.info/Members/zmoelnig/tests/deken-test.zip"
  - (cd tmp; unzip deken-test.zip; rm deken-test.zip)

script:
# 'deken upgrade' downloads files from the 'master' branch, so we can only use
# it, if this CI-build is actually run for this 'master' branch.
# if not, we just pip 'requiremements.txt' directly
  - if [[ "x${TRAVIS_PR_BRANCH:-${TRAVIS_BRANCH}}" != "xmaster" ]]; then "${PIP}" install -r developer/requirements.txt; else ~/bin/deken upgrade ; fi
  - ./developer/deken package -v000.dekenci tmp/deken-test
  - ./developer/deken package --dekformat 0 -v000.dekenci tmp/deken-test

after_script:
  - ls -l
  - ls -l tmp/
