language: python

python:
  - "2.6"
  - "3.6"

install:
  - mkdir -p ~/bin
  - curl https://raw.githubusercontent.com/pure-data/deken/master/developer/deken > ~/bin/deken
  - chmod u+x ~/bin/deken
  - ~/bin/deken

script:
  - echo ${PYTHON}
  - python --version
